[package]
name = "media_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
scraper = "0.18"
url = "2.5.4"
reqwest = "0.12.14"
serde_json = "1.0"
anyhow = "1.0.97"
